#!/bin/bash

./uninstall

rm -rf torcs-1.3.4
echo "remove done"

cp -r torcs.base torcs-1.3.4
#remove other drivers for more visibility during selection
rm -rf torcs-1.3.4/src/drivers/berniw*
rm -rf torcs-1.3.4/src/drivers/inferno*
rm -rf torcs-1.3.4/src/drivers/tita
rm -rf torcs-1.3.4/src/drivers/damned
echo "cp done"

cd torcs-1.3.4
./configure --enable-debug > /dev/null
make >& /dev/null
cd src/libs/raceengineclient
g++ -shared -o libraceengine.so singleplayer.o raceinit.o \
racemain.o racemanmenu.o racestate.o racegl.o raceengine.o raceresults.o \
-lracescreens -lrobottools -L../../../export/lib/ \
 -lalut -lvorbisfile -L/usr/lib
cd ../../../
make > /dev/null
echo "compil done"
sudo make install > /dev/null
sudo make datainstall > /dev/null
echo "install done"

cd ..
mkdir -p ~/.torcs/config/raceman/
cp xml/*.xml ~/.torcs/config/
mv ~/.torcs/config/quickrace.xml ~/.torcs/config/raceman/
echo "config done"

