#!/bin/bash


if [ ! -e torcs.base.tar.bz2 ]; then
   wget http://freefr.dl.sourceforge.net/project/torcs/all-in-one/1.3.4/torcs-1.3.4.tar.bz2 -O torcs.base.tar.bz2
fi

if [ ! -e torcs.base.tar.bz2 ]; then
   tar -xjvf torcs.base.tar.bz2
fi

if [ ! -e torcs.base ] ; then
cp -r torcs-1.3.4 torcs.base

fi

echo "done"
