#!/bin/bash

. path

trap sigusr1 SIGUSR1

sigusr1()
{
        rm -rf /dev/shm/sem.*
}


launch(){

lperf=0
index=$1
file="smile${index}.data"

for i in {1..900000}
do 
  torcs -r ~/.torcs/config/dtmrace${index}.xml > /dev/null &
  pid1=$!

  if [ $# -eq 2 ] ; then
    torcs -r ~/.torcs/config/dtmrace${index}.xml > /dev/null &
    pid2=$!
    torcs -r ~/.torcs/config/dtmrace${index}.xml > /dev/null &
    pid3=$!
    torcs -r ~/.torcs/config/dtmrace${index}.xml > /dev/null &
    pid4=$!
    wait $pid2 $pid3 $pid4
  fi

  wait $pid1

  episod=`cat $path/$file  | grep episode | sed 's/[^0-9]*//g'`
  perf=`cat $path/$file  | grep perf | sed 's/[^-0-9]*//g'`
  lsize=`cat $path/$file | grep -ve '\([^0-9]\|^\)0\([.]\|<\)' | wc -l`
  if [ $perf -ne $lperf  ] ; then
  	echo "episod : $episod | state learned : $lsize | perf : $perf"
  fi
  lperf=$perf
#  if [ $perf -lt -8000 ] && [ $episod -gt 70 ] ; then
#	echo "cannot converge, retry from scratch"
#	rm /usr/local/share/games/torcs/$file
#  fi
done

}

if [ $# -lt 1 ] ; then
	echo "Usage : $0 <index> <4core>"
	# <cpu>"
else
  launch $1 $2
fi



