#!/bin/bash


launch(){

index=$1
nbCPU=$2
file="smile${index}.data"

torcs -r ~/.torcs/config/dtmrace${index}.xml > /dev/null

for i in {1..900000}
do 
  lsize=`cat /usr/local/share/games/torcs/$file | grep -ve '\([^0-9]\|^\)0\([.]\|<\)' | wc -l`
  episod=`expr $i \* $nbCPU`
  echo "iter : $i | state learned : $lsize | simulated races :  $episod"
  pid=""
  for ((q=1; q <= $nbCPU ; q++))
  do
    torcs -r ~/.torcs/config/dtmrace${index}.xml > /dev/null &
    pid="$pid $!"
  done
  for p in "$pid"
  do
	  wait $p
  done
done

}


if [ ! $# -eq 2 ] ; then
	echo "Usage : $0 <index> <cpu>"
else
  launch $1 $2
fi



