#!/bin/bash

trap sigusr1 SIGUSR1

sigusr1()
{
	rm -rf /dev/shm/sem.*
}

launch(){

index=$1
cp ../torcs/xml/quickraceO.xml ~/.torcs/config/raceman/quickrace.xml
sed -i "s/SEDME/$index/" ~/.torcs/config/raceman/quickrace.xml
torcs -d
cp ../torcs/xml/quickrace.xml ~/.torcs/config/raceman/
}

if [ $# -lt 1 ] ; then
	echo "Usage : $0 <index>"
else
  launch $1
fi



