#!/bin/bash

sudo rm -rf /usr/local/share/games/torcs
sudo rm -rf /usr/local/bin/torcs
sudo rm -rf /usr/local/lib/torcs
rm -rf ~/.torcs/
rm -rf torcs-1.3.4
echo "remove done"
cp -r torcs.base torcs-1.3.4
echo "cp done"
cd torcs-1.3.4
cp -r ../lan src/drivers/lan
./configure --enable-debug > /dev/null
make > /dev/null
echo "compil done"
sudo make install > /dev/null
sudo make datainstall > /dev/null

