#!/bin/bash

sudo rm -rf /usr/local/share/games/torcs
sudo rm -rf /usr/local/bin/torcs
sudo rm -rf /usr/local/lib/torcs
rm -rf ~/.torcs/
rm -rf torcs-1.3.4
echo "remove done"
cp -r torcs.base torcs-1.3.4
echo "cp done"
cd torcs-1.3.4
cp -r ../driver src/drivers/smile
./configure --enable-debug > /dev/null
make > /dev/null
echo "compil done"
sudo make install > /dev/null
sudo make datainstall > /dev/null
echo "install done"

cd ..
mkdir -p ~/.torcs/config/raceman/
cp xml/*.xml ~/.torcs/config/
mv ~/.torcs/config/quickrace.xml ~/.torcs/config/raceman/
mv ~/.torcs/config/dtmrace.xml ~/.torcs/config/raceman/
echo "config done"

