#!/bin/bash

sudo rm -rf /usr/local/share/games/torcs/drivers/smile
sudo rm -rf /usr/local/lib/torcs/drivers/smile
sudo rm -rf torcs-1.3.4/src/drivers/smile
echo "remove done"
cd torcs-1.3.4
cp -r ../driver src/drivers/smile
make > /dev/null
echo "compil done"
sudo make installdirs > /dev/null

